apiVersion: v1
kind: Service
metadata:
  name: testapp
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: testapp
    k8s-app: testapp
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - name: testapp
      port: 8080
      targetPort: 8080
    